use serde::{Deserialize, Serialize};
use std::fs;
use std::path::PathBuf;
use std::sync::Mutex;
use std::time::{SystemTime, UNIX_EPOCH};
use tauri::{AppHandle, Manager};

/// Serializes every read-modify-write of a note file.
///
/// Geometry is flushed from a background thread (see `lib.rs`) while content
/// saves arrive on the main thread as IPC commands, so two full
/// read-modify-write cycles can genuinely interleave. Without this lock a note
/// dragged while a content save is in flight can have the typed text written
/// back from a stale in-memory copy.
static NOTE_IO: Mutex<()> = Mutex::new(());

fn lock_io() -> std::sync::MutexGuard<'static, ()> {
    // A panic while holding this guard would otherwise poison the lock and
    // make every later save fail; the data it guards is on disk, not in the
    // guard, so recovering is correct here.
    NOTE_IO.lock().unwrap_or_else(|e| e.into_inner())
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Position {
    pub x: f64,
    pub y: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Size {
    pub width: f64,
    pub height: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Note {
    pub id: String,
    pub title: String,
    pub content: String,
    pub color: String,
    pub position: Position,
    pub size: Size,
    /// Notes start with wrap off -- a file predating this field defaults the
    /// same way a freshly created note does (see `create_note_default`).
    #[serde(default)]
    pub wrap: bool,
    #[serde(default)]
    pub pinned: bool,
    /// Hidden via the note's own minimize button. Persisted so a minimized note
    /// stays minimized across a restart rather than reappearing on screen.
    #[serde(default)]
    pub minimized: bool,
    pub created_at: u64,
    pub updated_at: u64,
}

#[derive(Debug, Clone, Deserialize)]
pub struct NoteFields {
    pub id: String,
    pub title: String,
    pub content: String,
    pub color: String,
    pub wrap: bool,
}

fn now_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_millis() as u64)
        .unwrap_or(0)
}

pub fn notes_dir(app: &AppHandle) -> Result<PathBuf, String> {
    let dir = app
        .path()
        .app_data_dir()
        .map_err(|e| format!("app data dir unavailable: {e}"))?
        .join("notes");
    if !dir.exists() {
        fs::create_dir_all(&dir).map_err(|e| format!("could not create {}: {e}", dir.display()))?;
    }
    Ok(dir)
}

/// Note ids are UUIDs generated by `create_note_default`, and they are also the
/// filename. Validating rather than trusting keeps a malformed or crafted id
/// (`../..`) from ever addressing a file outside the notes directory.
fn note_path(app: &AppHandle, id: &str) -> Result<PathBuf, String> {
    uuid::Uuid::parse_str(id).map_err(|_| format!("invalid note id: {id}"))?;
    Ok(notes_dir(app)?.join(format!("{id}.json")))
}

fn read_note(app: &AppHandle, id: &str) -> Result<Note, String> {
    let path = note_path(app, id)?;
    let text = fs::read_to_string(&path).map_err(|e| e.to_string())?;
    serde_json::from_str(&text).map_err(|e| e.to_string())
}

/// Writes via a temp file plus a rename, so an interrupted write leaves the
/// previous note intact instead of a truncated file that `list_notes` would
/// silently drop.
fn write_note(app: &AppHandle, note: &Note) -> Result<(), String> {
    let mut note = note.clone();
    note.updated_at = now_millis();
    let path = note_path(app, &note.id)?;
    let text = serde_json::to_string_pretty(&note).map_err(|e| e.to_string())?;
    let tmp = path.with_extension("json.tmp");
    fs::write(&tmp, text).map_err(|e| e.to_string())?;
    fs::rename(&tmp, &path).map_err(|e| {
        let _ = fs::remove_file(&tmp);
        e.to_string()
    })
}

pub fn list_notes(app: &AppHandle) -> Vec<Note> {
    let _guard = lock_io();
    let Ok(dir) = notes_dir(app) else {
        return Vec::new();
    };
    let mut notes = Vec::new();
    if let Ok(entries) = fs::read_dir(&dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("json") {
                continue;
            }
            match fs::read_to_string(&path) {
                Ok(text) => match serde_json::from_str::<Note>(&text) {
                    Ok(note) => notes.push(note),
                    // A note that won't parse is invisible in the UI, so say so
                    // rather than letting it disappear without a trace.
                    Err(e) => eprintln!("skipping unreadable note {}: {e}", path.display()),
                },
                Err(e) => eprintln!("skipping unreadable note {}: {e}", path.display()),
            }
        }
    }
    notes.sort_by_key(|n| n.created_at);
    notes
}

pub fn load_note(app: &AppHandle, id: &str) -> Result<Note, String> {
    let _guard = lock_io();
    read_note(app, id)
}

pub fn save_note_to_disk(app: &AppHandle, note: &Note) -> Result<(), String> {
    let _guard = lock_io();
    write_note(app, note)
}

pub fn update_note_fields(app: &AppHandle, fields: &NoteFields) -> Result<(), String> {
    let _guard = lock_io();
    let mut note = read_note(app, &fields.id)?;
    note.title = fields.title.clone();
    note.content = fields.content.clone();
    note.color = fields.color.clone();
    note.wrap = fields.wrap;
    write_note(app, &note)
}

pub fn update_note_pinned(app: &AppHandle, id: &str, pinned: bool) {
    let _guard = lock_io();
    if let Ok(mut note) = read_note(app, id) {
        note.pinned = pinned;
        let _ = write_note(app, &note);
    }
}

/// No-op when the flag already matches, so the startup pass and every window
/// restore don't rewrite files that have nothing to change.
pub fn update_note_minimized(app: &AppHandle, id: &str, minimized: bool) {
    let _guard = lock_io();
    if let Ok(mut note) = read_note(app, id) {
        if note.minimized == minimized {
            return;
        }
        note.minimized = minimized;
        let _ = write_note(app, &note);
    }
}

pub fn update_note_geometry(
    app: &AppHandle,
    id: &str,
    position: Option<Position>,
    size: Option<Size>,
) {
    let _guard = lock_io();
    if let Ok(mut note) = read_note(app, id) {
        if let Some(p) = position {
            note.position = p;
        }
        if let Some(s) = size {
            note.size = s;
        }
        let _ = write_note(app, &note);
    }
}

pub fn delete_note(app: &AppHandle, id: &str) -> Result<(), String> {
    let _guard = lock_io();
    let path = note_path(app, id)?;
    fs::remove_file(path).map_err(|e| e.to_string())
}

pub fn create_note_default(offset: f64) -> Note {
    let id = uuid::Uuid::new_v4().to_string();
    let now = now_millis();
    Note {
        id,
        title: String::new(),
        content: String::new(),
        color: "#fff59d".to_string(),
        position: Position {
            x: 120.0 + offset,
            y: 120.0 + offset,
        },
        wrap: false,
        pinned: false,
        minimized: false,
        size: Size {
            width: 260.0,
            height: 260.0,
        },
        created_at: now,
        updated_at: now,
    }
}
